server:
  port: 8585

spring:
  application:
    name: log-events
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/alertsdb;DB_CLOSE_DELAY=1000
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

app:
  log-events:
    alert-threshold-ms: 5
    table-rows-writeoff-count: 100

